### PR TITLE
Upgrade to babel 4

### LINKED ISSUE #24: Npm start doesnt work on latest Node
```
> test@1.0.1 start /Users/redacted/redacted/redacted/component_boilerplate
> gulp watch

[13:55:13] Failed to load external module @babel/register
[13:55:13] Requiring external module babel-register
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
at fs.js:27:26
at req_ (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/node_modules/natives/index.js:137:5)
at Object.req [as require] (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/node_modules/natives/index.js:54:10)
at Object.<anonymous> (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
at Module._compile (internal/modules/cjs/loader.js:774:30)
at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Object.require.extensions.<computed> [as .js] (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/babel-register/lib/node.js:152:7)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Module.require (internal/modules/cjs/loader.js:681:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.1 start: `gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

running on Node v12.4.0

would be awesome if this was fixed on a repo level :) is there any way to fix this without downgrading the Node version I use?

### PR DESCRIPTION
**Pull request by iRyusa**
Most likely to fix #24 & #25

### CODE REVIEW

**Comment by AndyBaird** [comment]
From the branch **fix/latest-node** I ran **npm install** and this is what I see:
`SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:72:
/usr/local/include/Block.h:16:3: error: Never include this file directly. Use <lzma.h> instead.
#       error Never include this file directly. Use <lzma.h> instead.
        ^
/usr/local/include/Block.h:93:2: error: unknown type name 'lzma_check'
        lzma_check check;
        ^
/usr/local/include/Block.h:148:2: error: unknown type name 'lzma_vli'
        lzma_vli compressed_size;
        ^
/usr/local/include/Block.h:172:2: error: unknown type name 'lzma_vli'
        lzma_vli uncompressed_size;
        ^
/usr/local/include/Block.h:200:2: error: unknown type name 'lzma_filter'
        lzma_filter *filters;
        ^
/usr/local/include/Block.h:217:20: error: use of undeclared identifier 'LZMA_CHECK_SIZE_MAX'
        uint8_t raw_check[LZMA_CHECK_SIZE_MAX];
                          ^
/usr/local/include/Block.h:231:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int3;
        ^
/usr/local/include/Block.h:232:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int4;
        ^
/usr/local/include/Block.h:233:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int5;
        ^
/usr/local/include/Block.h:234:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int6;
        ^
/usr/local/include/Block.h:235:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int7;
        ^
/usr/local/include/Block.h:236:2: error: unknown type name 'lzma_vli'
        lzma_vli reserved_int8;
        ^
/usr/local/include/Block.h:237:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum1;
        ^
/usr/local/include/Block.h:238:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum2;
        ^
/usr/local/include/Block.h:239:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum3;
        ^
/usr/local/include/Block.h:240:2: error: unknown type name 'lzma_reserved_enum'
        lzma_reserved_enum reserved_enum4;
        ^
/usr/local/include/Block.h:261:2: error: unknown type name 'lzma_bool'
        lzma_bool ignore_check;
        ^
/usr/local/include/Block.h:263:2: error: unknown type name 'lzma_bool'
        lzma_bool reserved_bool2;
        ^
/usr/local/include/Block.h:264:2: error: unknown type name 'lzma_bool'
        lzma_bool reserved_bool3;
        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"`

**Comment by AndyBaird** [comment]
I fixed the above issue with using info from this thread https://github.com/golang/go/issues/25240.
Evidently when I migrated a long time ago the migration assistant failed to clean up some files.

**Comment by AndyBaird** [comment]
Continuing the tutorial after the npm build I receive this: 
image

**Comment by AndyBaird** [comment]
Continuing the tutorial after npm install I received the following: 
image

**Comment by AndyBaird** [comment]
I confirmed the files were there and ran it again and the error resolved. That was weird, but the package updates do appear to correct the issue

**Comment by sotrustmtg** [comment]
> Most likely to fix #24 & #25

I can confirm, upgrading gulp to 4 fixed my "npm start" issue.

**Pull request merged**
